// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGM2CGXwsTf6rCKkjMSW7kyqnhxsOuoxY',
    appId: '1:14169052617:web:b19d09fcc8740879b34418',
    messagingSenderId: '14169052617',
    projectId: 'garagecom-3dc95',
    authDomain: 'garagecom-3dc95.firebaseapp.com',
    storageBucket: 'garagecom-3dc95.firebasestorage.app',
    measurementId: 'G-CHZVCCRTH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSoma8Pwtc4WNeMZXLF_Ixc6l-VybwBnQ',
    appId: '1:14169052617:android:b08a36fa9d4d4509b34418',
    messagingSenderId: '14169052617',
    projectId: 'garagecom-3dc95',
    storageBucket: 'garagecom-3dc95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTg-VA6KKgxzNo9_-_pcrzkWwVj64faG0',
    appId: '1:14169052617:ios:3a0f5e2c386a9bb9b34418',
    messagingSenderId: '14169052617',
    projectId: 'garagecom-3dc95',
    storageBucket: 'garagecom-3dc95.firebasestorage.app',
    iosBundleId: 'com.example.garagecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTg-VA6KKgxzNo9_-_pcrzkWwVj64faG0',
    appId: '1:14169052617:ios:3a0f5e2c386a9bb9b34418',
    messagingSenderId: '14169052617',
    projectId: 'garagecom-3dc95',
    storageBucket: 'garagecom-3dc95.firebasestorage.app',
    iosBundleId: 'com.example.garagecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGM2CGXwsTf6rCKkjMSW7kyqnhxsOuoxY',
    appId: '1:14169052617:web:eae64f1bf731e783b34418',
    messagingSenderId: '14169052617',
    projectId: 'garagecom-3dc95',
    authDomain: 'garagecom-3dc95.firebaseapp.com',
    storageBucket: 'garagecom-3dc95.firebasestorage.app',
    measurementId: 'G-0QHTHXQTR0',
  );
}
